#data configs
data:
  exchange: "binance"
  symbols: 
    - "BTC/USDT"
    # - "ETH/USDT" # add more symbols as needed
  timeframe: "1h"
  total_years: 5
  start_date: "2019-01-01"
  end_date: "2024-01-01"
  max_fill_candles: 2
  #anomaly detection configs
  anomaly_detection:
    rolling_window: 30
    wick_multiplier: 5.0
    wick_percent: 0.75

#feature configs
features:
  price:
    log_return_short_period: 1   
    log_return_long_period: 6
    ema_window: 20              
    dist_high_low_window: 24

  momentum:
    rsi_window: 14
    adx_window: 14

  volatility:
    atr_window: 14                 
    vol_ratio_short_window: 24     
    vol_ratio_long_window: 72      
    sharpe_window: 24              
    periods_per_year: 8760 

  volume:
    zscore_window: 20             

#path configs
paths:
  raw_dir:       data/raw
  processed_dir:  data/processed
  feature_engineered_dir: data/features
  logs_dir:      logs
  feature_graphs_dir:    graphs/features


