#data configs
data:
  exchange: "binance"
  symbols: 
    - "BTC/USDT"
    # - "ETH/USDT" # add more symbols as needed
  timeframe: "1h"
  total_years: 5
  start_date: "2021-06-01"
  end_date: "2026-06-01"
  max_fill_candles: 2
  vol_rolling_days: 30
  #anomaly detection configs
  anomaly_detection:
    rolling_window: 30
    wick_multiplier: 5.0
    wick_percent: 0.75


#path configs
paths:
  raw_dir:       data/raw
  processed_dir:  data/processed


